name: gaslow_app
description: GasLow App

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.2
  redux_thunk: ^0.2.0
  url_launcher: ^3.0.3
  location: ^1.3.4
  intl: ^0.15.7
  geocoder: ^0.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.6.0"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-Bold.ttf
          weight: 700

  assets:
    - assets/station_logos/

# To update icons:
# flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
