name: gaslow_app
description: GasLow App

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.6.0
  redux_thunk: ^0.3.0
  url_launcher: ^5.4.1
  location: ^2.3.5
  intl: ^0.16.1
  geocoder: ^0.2.1
  latlong: ^0.6.1
  http: ^0.12.0+4
  google_maps_flutter: ^0.5.22
  firebase_admob: ^0.9.0+10
  shared_preferences: ^0.5.6+1
  firebase_analytics: ^5.0.11
  #esys_flutter_share: ^1.0.2
  app_review: ^1.0.0
  share: ^0.6.3+5
  get_it: ^3.1.0
  rate_my_app: ^0.5.0+3
  animated_text_kit: ^1.3.1
  scroll_to_index: ^1.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  test: ^1.5.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Syncopate
      fonts:
        - asset: fonts/Syncopate-Regular.ttf
        - asset: fonts/Syncopate-Bold.ttf
          weight: 700

  assets:
    - assets/station_logos/
    - assets/secrets.yml

# To update icons:
# flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
