name: gaslow_app
description: GasLow App
version: 1.4.1+26

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.8.2
  redux_thunk: ^0.4.0
  url_launcher: ^6.0.3
  location: ^4.3.0
  intl: ^0.17.0
  geocoding: ^2.0.1
  http: ^0.13.1
  google_maps_flutter: ^2.1.1
  google_mobile_ads: ^0.13.2+1
  shared_preferences: ^2.0.11
  firebase_analytics: ^8.0.0
  #esys_flutter_share: ^1.0.2
  app_review: ^2.1.1
  share: ^2.0.4
  get_it: ^7.2.0
  rate_my_app: ^1.1.0+1
  animated_text_kit: ^4.2.1
  scroll_to_index: ^2.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  test:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Regular.ttf
        - asset: fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Syncopate
      fonts:
        - asset: fonts/Syncopate-Regular.ttf
        - asset: fonts/Syncopate-Bold.ttf
          weight: 700

  assets:
    - assets/station_logos/
    - assets/secrets.yml

# To update icons:
# flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
